roxygen2::roxygenise("tsf")
install.packages("tsf", repos = NULL, type = "source")
detach("package:tsf", unload = TRUE)
tsf::runApp(4005)
tinytest::test_package("tsf")

library(shiny)
library(DT)
library(shinydashboard)
library(shinyWidgets)
library(shinyjs)
library(shinytest2)
library(rootSolve)
library(ggplot2)
library(patchwork)
library(R6)
library(sensitivity)
library(openxlsx)
library(callr)
library(cowplot)
library(RColorBrewer)
library(plotly)
library(ks)
# host = 4.0,
# dye = 6,
# kHD = 1.7e01
files <- list.files("./tsf/R", full.names = TRUE)
trash <- lapply(files, source)
runApp(4005)
