roxygen2::roxygenise("tsf")
devtools::install("tsf", build_vignettes = TRUE, upgrade = "never")
#install.packages("tsf", repos = NULL, type = "source")
detach("package:tsf", unload = TRUE)
library(tsf)
tsf::runApp(3838)
#tinytest::test_package("tsf")	