library(shiny)
library(DT)
library(shinydashboard)
library(shinyWidgets)
library(shinyjs)
library(rootSolve)
library(ggplot2)
library(patchwork)
library(R6)
library(sensitivity)
library(openxlsx)
library(future)
library(promises)
library(tsf)

shinyApp(tsf:::uiInterface(), tsf:::server)